# Docker Compose para AWS ECS/Fargate
version: '3.8'

services:
  monjaro-app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/monjaro-app:${VERSION}
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - PORT=8000
      - KOREPAY_SECRET_KEY=${KOREPAY_SECRET_KEY}
      - KOREPAY_RANDOM_KEY=${KOREPAY_RANDOM_KEY}
      - KOREPAY_SIMULATION_MODE=${KOREPAY_SIMULATION_MODE:-false}
      - CPF_API_TOKEN=${CPF_API_TOKEN}
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/monjaro-app
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - monjaro-app
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/monjaro-nginx
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16